 

<div id="wrapper">
	<div id="header">
    
        <div id="site_title">
            <a href="index.php" target="_parent"><img src="images/logo.png" alt="logo" /><span>YOUR TRIP GOES HERE</span></a>
        </div> <!-- end of site_title -->
        
        <div id="menu">
            <ul>
                <li><a href="index.php" target="_parent" class="current">Home</a></li>
                <li><a href="search.php" target="_parent">Search Flights</a></li>
				<li><a href="yourBooking.php">Your Booking</a></li>
                <!-- <li><a href="about.php">About</a></li> -->
                <li class="last"><a href="contact.php">Contact</a></li>
            </ul>    	
	    </div> <!-- end of menu -->
    </div> <!-- end of header -->
